apiVersion: apps/v1
kind: Deployment
metadata:
  name: taller-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taller-k8s
  template:
    metadata:
      labels:
        app: taller-k8s
    spec:
      containers:
        - name: taller-k8s
          image: odzen2000/k8s:f715d8 #old image
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: taller-k8s-service
spec:
  selector:
    app: taller-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
