name: Deploy to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
      
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set GitHub env variables
      shell: bash
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Build
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ env.IMAGE_TAG }}

    - name: Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ env.IMAGE_TAG }}